apiVersion: v1
kind: ServiceAccount
metadata:
  name: kafka-client-sa
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::873543029686:role/eksctl-kafka-client-cluster-addon-iamservicea-Role1-OILESK310yYh
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  namespace: default
data:
  bootstrap.servers: "your-msk-bootstrap-broker-endpoints"
  group.id: "kafka-msk-client-group"
  region: "us-east-1"
  secret.name: "MSK-SCRAM-User-Secret"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-client
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kafka-client
  template:
    metadata:
      labels:
        app: kafka-client
    spec:
      serviceAccountName: kafka-client-sa
      containers:
      - name: kafka-client
        image: 873543029686.dkr.ecr.us-east-1.amazonaws.com/kafka-client:v20250419190248
        env:
        - name: BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              name: kafka-config
              key: bootstrap.servers
        - name: GROUP_ID
          valueFrom:
            configMapKeyRef:
              name: kafka-config
              key: group.id
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: kafka-config
              key: region
        - name: SECRET_NAME
          valueFrom:
            configMapKeyRef:
              name: kafka-config
              key: secret.name
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "256Mi"
