apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  namespace: default
data:
  bootstrap.servers: "b-2.democluster1.smmm8q.c19.kafka.us-east-1.amazonaws.com:9098,b-3.democluster1.smmm8q.c19.kafka.us-east-1.amazonaws.com:9098,b-1.democluster1.smmm8q.c19.kafka.us-east-1.amazonaws.com:9098"
  group.id: "kafka-msk-client-group"
  region: "us-east-1"
  secret.name: "MSK-SCRAM-User-Secret"
